### ISSUE TITLE
Don't encourage command strings

### ISSUE THREAD

**Issue by hybrist** [groupon-testium/subprocess#1]
1. They make it look like arbitrary commands are supported (including `|` etc.)
2. Handling quoting and escaping correctly will be an edge case nightmare

**Comment by EndangeredMassa** [comment]
Ah, good point. It's just so much nicer to type. I'll switch this.

**Comment by EndangeredMassa** [comment]
https://github.com/groupon-testium/subprocess/commit/f9b4db6736ea49f410a1936dfbe4996f39069b24
