### ISSUE TITLE
Track processes to be cleaned up

### ISSUE THREAD

**Issue by hybrist** [groupon-testium/subprocess#2]
Right now one uncaughtException handler is added for every child spawned and it's always executed - even when the child already exited. This might lead to confusing errors being logged to the terminal.

**Comment by EndangeredMassa** [comment]
https://github.com/groupon-testium/subprocess/commit/c4e033126dc47d2c71ed1ac3c121aaff3f3ca92c

**Comment by hybrist** [comment]
I think you linked the wrong commit here. I'm assuming this one is the right now: https://github.com/groupon-testium/subprocess/commit/6411dc4fd19a43df18d9de5b749c30f6c7535b23

**Comment by hybrist** [comment]
P.S.: For things like this adding `Fixes #2` or even `Fixes https://github.com/groupon-testium/subprocess/issues/2` to the long commit message ensures that the commit and the issue are in sync.
