### ISSUE TITLE
Use _.merge instead of deep-extend

### ISSUE THREAD

**Issue by hybrist** [groupon-testium/subprocess#3]
It seems like the extra dependency on `deep-extend` could be removed.

**Comment by EndangeredMassa** [comment]
`_.merge` appears to only do a shallow merge. When I use that, my tests fail. That's why I brought in `deep-extend`.

**Comment by hybrist** [comment]
Weird, the whole difference between `_.extend` and `_.merge` should be that `_.merge` is doing a "deep extend":

``` bash
> node -p 'require("lodash").merge({ x: { y: 1, z: 2 }, a: 10 }, { x: { y: 3 }, b: 11 })'
{ x: { y: 3, z: 2 }, a: 10, b: 11 }
```

**Comment by EndangeredMassa** [comment]
Ah, there's something special about `process.env`. Lodash won't retain the properties of it, but deep-extend will. If I clone `process.env`, lodash works fine.

**Comment by EndangeredMassa** [comment]
Fixed: https://github.com/groupon-testium/subprocess/commit/4b98f56e57bbc69a21d7a503c0749b7f9d75cb03

**Comment by hybrist** [comment]
Yeah, got bitten by that in localize, too. `lodash@3.x` got really serious about properties, e.g. does `hasOwnProperty` checks everywhere.
