### ISSUE TITLE
Make syntax match async.auto

### ISSUE THREAD

**Issue by hybrist** [groupon-testium/subprocess#4]
Since we already call out the similarity in the README, it seems straight forward to do:

``` js
subprocess({
  x: { /* x options */ },
  y: [ 'x', { /* y options */ } ]
}, function(error, procs) {
});
```

**Comment by EndangeredMassa** [comment]
I prefer the current interface, but agree that some might expect the `async.auto` interface.

**Comment by hybrist** [comment]
I agree that the current interface is cleaner. Maybe it's enough to call out the difference in the README?

**Comment by EndangeredMassa** [comment]
How's this? https://github.com/groupon-testium/subprocess/commit/88ee4c3913671c2d25ac9109ea9a9d9799c2b001

**Comment by hybrist** [comment]
Nice! :+1:
