### ISSUE TITLE
Minor stylistic nit-picking/questions

### ISSUE THREAD

**Issue by hybrist** [groupon-testium/subprocess#5]
- [x] [`\%` looks like an "invalid" escape sequence](https://github.com/groupon-testium/subprocess/blob/5a149c3b22fdb2c30d5ef0f64d649fd0e47079ed/src/spawn.coffee#L10)
- [x] [Unnecessary extend instead of creation the complete object](https://github.com/groupon-testium/subprocess/blob/5a149c3b22fdb2c30d5ef0f64d649fd0e47079ed/src/spawn.coffee#L15-L18)
- [x] [Add back commented out debug line (or remove)](https://github.com/groupon-testium/subprocess/blob/5a149c3b22fdb2c30d5ef0f64d649fd0e47079ed/src/verify.coffee#L71)
- [x] [Is there a reason the log file is opened with `w+` instead of just `w`?](https://github.com/groupon-testium/subprocess/blob/5a149c3b22fdb2c30d5ef0f64d649fd0e47079ed/src/log.coffee#L8)

**Comment by EndangeredMassa** [comment]
Unnecessary extend: https://github.com/groupon-testium/subprocess/commit/4b98f56e57bbc69a21d7a503c0749b7f9d75cb03

**Comment by EndangeredMassa** [comment]
Debug line: https://github.com/groupon-testium/subprocess/commit/6ca24942b70b0a56d40f68565b3dfbb888ed3504

**Comment by EndangeredMassa** [comment]
Log file flag: https://github.com/groupon-testium/subprocess/commit/da19976e20797cd30aa40cc746f4382104128525

**Comment by EndangeredMassa** [comment]
Escape sequence: https://github.com/groupon-testium/subprocess/commit/c4e033126dc47d2c71ed1ac3c121aaff3f3ca92c

**Comment by hybrist** [comment]
:+1:
